// GENERATED FILE — do not edit by hand.
//
// Source: docs/catalog/agenthub-market.json
// Regenerate: npm run catalog:sync
//
// This is the desktop's offline fallback for the market catalog. It is the same
// data the remote document carries; which agents are *runnable* is decided in
// profiles.ts, not here.

import type { MarketEntryDraft } from "../../shared/agenthub-market";

/** Date the catalog was last edited upstream, for display only. */
export const MARKET_UPDATED_AT = "2026-09-15";

export const MARKET_ENTRIES: readonly MarketEntryDraft[] = [
  {
    id: "claude-code",
    rank: 1,
    name: "Claude Code",
    vendor: "Anthropic",
    category: "official",
    role: { zh: "代码智能体", en: "Coding agent" },
    description: {
      zh: "Anthropic 官方命令行编码智能体，用户量最大；等待只读参数与凭据隔离验证后接入。",
      en: "Anthropic's official coding CLI and the most widely used agent today; waiting for read-only flag and credential-isolation verification.",
    },
    docsUrl: "https://docs.anthropic.com/en/docs/claude-code",
    installHint: "npm install -g @anthropic-ai/claude-code",
    binaries: {
      win: ["claude.cmd", "claude.exe", "claude"],
      unix: ["claude"],
    },
    permissions: ["planned"],
  },
  {
    id: "codex",
    rank: 2,
    name: "Codex CLI",
    vendor: "OpenAI",
    category: "official",
    role: { zh: "代码智能体", en: "Coding agent" },
    description: {
      zh: "OpenAI 官方命令行编码智能体，计划使用官方 read-only 沙箱接入，不使用绕过审批的开关。",
      en: "OpenAI's official coding CLI. AgentHub plans to use its official read-only sandbox and never a bypass-approvals flag.",
    },
    docsUrl: "https://github.com/openai/codex",
    installHint: "npm install -g @openai/codex",
    binaries: {
      win: ["codex.cmd", "codex.exe", "codex"],
      unix: ["codex"],
    },
    permissions: ["read-only-sandbox", "no-write", "planned"],
  },
  {
    id: "gemini-cli",
    rank: 3,
    name: "Gemini CLI",
    vendor: "Google",
    category: "official",
    role: { zh: "终端智能体", en: "Terminal agent" },
    description: {
      zh: "Google 官方开源终端智能体，支持工具白名单与 MCP，计划用只读参数接入。",
      en: "Google's official open-source terminal agent with tool allowlists and MCP support; planned read-only integration.",
    },
    docsUrl: "https://github.com/google-gemini/gemini-cli",
    installHint: "npm install -g @google/gemini-cli",
    binaries: {
      win: ["gemini.cmd", "gemini.exe", "gemini"],
      unix: ["gemini"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "copilot-cli",
    rank: 4,
    name: "GitHub Copilot CLI",
    vendor: "GitHub",
    category: "vendor-cli",
    role: { zh: "厂商编码智能体", en: "Vendor coding agent" },
    description: {
      zh: "GitHub 官方命令行编码智能体，可直接复用已有的 Copilot 订阅。",
      en: "GitHub's official coding CLI; reuses an existing Copilot subscription.",
    },
    docsUrl: "https://github.com/github/copilot-cli",
    installHint: "npm install -g @github/copilot",
    binaries: {
      win: ["copilot.cmd", "copilot.exe", "copilot"],
      unix: ["copilot"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "cursor-agent",
    rank: 5,
    name: "Cursor CLI",
    vendor: "Cursor",
    category: "vendor-cli",
    role: { zh: "厂商编码智能体", en: "Vendor coding agent" },
    description: {
      zh: "Cursor 的命令行智能体，可在终端复用编辑器账号与项目规则。",
      en: "Cursor's command-line agent; reuses the editor account and project rules from the terminal.",
    },
    docsUrl: "https://cursor.com/cli",
    installHint: "按 Cursor CLI 官方文档安装",
    binaries: {
      win: ["cursor-agent.cmd", "cursor-agent"],
      unix: ["cursor-agent"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "opencode",
    rank: 6,
    name: "OpenCode",
    vendor: "SST",
    category: "open-source",
    role: { zh: "开源终端智能体", en: "Open-source terminal agent" },
    description: {
      zh: "开源终端编码智能体，可自由切换模型提供商，社区活跃。",
      en: "Open-source terminal coding agent with pluggable model providers and an active community.",
    },
    docsUrl: "https://github.com/sst/opencode",
    installHint: "npm install -g opencode-ai",
    binaries: {
      win: ["opencode.cmd", "opencode.exe", "opencode"],
      unix: ["opencode"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "cline",
    rank: 7,
    name: "Cline CLI",
    vendor: "Cline",
    category: "open-source",
    role: { zh: "开源编码智能体", en: "Open-source coding agent" },
    description: {
      zh: "知名开源编码智能体的命令行版本，行为透明、可逐步确认。",
      en: "The command-line build of a well-known open-source coding agent; transparent and step-confirmable.",
    },
    docsUrl: "https://github.com/cline/cline",
    installHint: "npm install -g cline",
    binaries: {
      win: ["cline.cmd", "cline"],
      unix: ["cline"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "aider",
    rank: 8,
    name: "Aider",
    vendor: "Aider",
    category: "open-source",
    role: { zh: "开源代码助手", en: "Open-source pair programmer" },
    description: {
      zh: "以 Git 为中心的配对编程工具，每步改动都可回退，适合审查型任务。",
      en: "A git-centric pair programmer whose every change is revertible — well suited to review-style tasks.",
    },
    docsUrl: "https://aider.chat/",
    installHint: "python -m pip install aider-install && aider-install",
    binaries: {
      win: ["aider.exe", "aider"],
      unix: ["aider"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "qwen-code",
    rank: 9,
    name: "Qwen Code",
    vendor: "阿里云",
    category: "china-ecosystem",
    role: { zh: "终端智能体", en: "Terminal agent" },
    description: {
      zh: "通义千问官方命令行智能体，中文场景与国内模型接入更顺畅。",
      en: "Alibaba's official Qwen terminal agent; smoother Chinese-language and mainland-model setup.",
    },
    docsUrl: "https://github.com/QwenLM/qwen-code",
    installHint: "npm install -g @qwen-code/qwen-code",
    binaries: {
      win: ["qwen.cmd", "qwen.exe", "qwen"],
      unix: ["qwen"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "goose",
    rank: 10,
    name: "Goose",
    vendor: "Block",
    category: "open-source",
    role: { zh: "开源本地智能体", en: "Open-source local agent" },
    description: {
      zh: "Block 开源的本地执行智能体，扩展生态成熟，可完全本地运行。",
      en: "Block's open-source local agent with a mature extension ecosystem and fully local operation.",
    },
    docsUrl: "https://github.com/block/goose",
    installHint: "按 Goose 官方文档安装 CLI",
    binaries: {
      win: ["goose.exe", "goose"],
      unix: ["goose"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "crush",
    rank: 11,
    name: "Crush",
    vendor: "Charm",
    category: "open-source",
    role: { zh: "开源终端智能体", en: "Open-source terminal agent" },
    description: {
      zh: "Charm 出品的开源终端编码智能体，界面精致、可自由切换模型提供商；尚未审核其非交互运行与只读参数，暂不接入。",
      en: "Charm's open-source terminal coding agent with a polished UI and swappable model providers; its non-interactive and read-only behaviour is not reviewed yet, so it is not connectable.",
    },
    docsUrl: "https://github.com/charmbracelet/crush",
    installHint: "npm install -g @charmland/crush",
    binaries: {
      win: ["crush.cmd", "crush.exe", "crush"],
      unix: ["crush"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "auggie",
    rank: 12,
    name: "Auggie CLI",
    vendor: "Augment Code",
    category: "vendor-cli",
    role: { zh: "厂商编码智能体", en: "Vendor coding agent" },
    description: {
      zh: "Augment Code 的命令行智能体，可复用它在大型代码库上的检索能力；等待只读参数验证后接入。",
      en: "Augment Code's command-line agent, reusing its retrieval on large codebases; waiting for read-only flag verification.",
    },
    docsUrl: "https://docs.augmentcode.com/",
    installHint: "npm install -g @augmentcode/auggie",
    binaries: {
      win: ["auggie.cmd", "auggie"],
      unix: ["auggie"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "amp",
    rank: 13,
    name: "Amp",
    vendor: "Sourcegraph",
    category: "vendor-cli",
    role: { zh: "厂商编码智能体", en: "Vendor coding agent" },
    description: {
      zh: "Sourcegraph 的命令行编码智能体，自动更新较频繁；等待只读参数验证后接入。",
      en: "Sourcegraph's command-line coding agent, updated frequently; waiting for read-only flag verification.",
    },
    docsUrl: "https://ampcode.com/",
    installHint: "npm install -g @sourcegraph/amp",
    binaries: {
      win: ["amp.cmd", "amp.exe", "amp"],
      unix: ["amp"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "droid",
    rank: 14,
    name: "Droid CLI",
    vendor: "Factory",
    category: "vendor-cli",
    role: { zh: "厂商编码智能体", en: "Vendor coding agent" },
    description: {
      zh: "Factory 官方的命令行编码智能体，npm 包名为 droid；等待只读参数验证后接入。",
      en: "Factory's official command-line coding agent, published on npm as droid; waiting for read-only flag verification.",
    },
    docsUrl: "https://docs.factory.ai/",
    installHint: "npm install -g droid",
    binaries: {
      win: ["droid.cmd", "droid.exe", "droid"],
      unix: ["droid"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "kilocode",
    rank: 15,
    name: "Kilo Code CLI",
    vendor: "Kilo Code",
    category: "open-source",
    role: { zh: "开源编码智能体", en: "Open-source coding agent" },
    description: {
      zh: "Kilo Code 的命令行版本，装好后有 kilo 和 kilocode 两个命令名；等待只读参数验证后接入。",
      en: "The command-line build of Kilo Code, which installs both a kilo and a kilocode command; waiting for read-only flag verification.",
    },
    docsUrl: "https://docs.kilocode.ai/",
    installHint: "npm install -g @kilocode/cli",
    binaries: {
      win: ["kilo.cmd", "kilo", "kilocode.cmd", "kilocode"],
      unix: ["kilo", "kilocode"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "roo-cli",
    rank: 16,
    name: "Roo Code CLI",
    vendor: "Roo Code",
    category: "open-source",
    role: { zh: "开源编码智能体", en: "Open-source coding agent" },
    description: {
      zh: "Roo Code 的命令行版本，来自成熟的开源 VS Code 智能体项目；等待只读参数验证后接入。",
      en: "The command-line build of Roo Code, a mature open-source VS Code agent; waiting for read-only flag verification.",
    },
    docsUrl: "https://github.com/RooCodeInc/Roo-Code",
    installHint: "npm install -g roo-cli",
    binaries: {
      win: ["roo.cmd", "roo"],
      unix: ["roo"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "continue-cli",
    rank: 17,
    name: "Continue CLI",
    vendor: "Continue",
    category: "open-source",
    role: { zh: "开源编码智能体", en: "Open-source coding agent" },
    description: {
      zh: "开源编程助手 Continue 的命令行版本，装好后命令名是 cn；等待只读参数验证后接入。",
      en: "The command-line build of the open-source Continue assistant, installed as the cn command; waiting for read-only flag verification.",
    },
    docsUrl: "https://docs.continue.dev/",
    installHint: "npm install -g @continuedev/cli",
    binaries: {
      win: ["cn.cmd", "cn.exe", "cn"],
      unix: ["cn"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "codebuddy-code",
    rank: 18,
    name: "CodeBuddy Code",
    vendor: "腾讯云",
    category: "china-ecosystem",
    role: { zh: "厂商编码智能体", en: "Vendor coding agent" },
    description: {
      zh: "腾讯云 CodeBuddy 的官方命令行智能体，除 npm 外还提供 Windows 原生安装脚本；等待只读参数验证后接入。",
      en: "Tencent Cloud's official CodeBuddy command-line agent, which also offers a native Windows installer; waiting for read-only flag verification.",
    },
    docsUrl: "https://www.codebuddy.cn/docs/cli/installation",
    installHint: "npm install -g @tencent-ai/codebuddy-code",
    binaries: {
      win: ["codebuddy.cmd", "codebuddy.exe", "codebuddy", "cbc.cmd", "cbc"],
      unix: ["codebuddy", "cbc"],
    },
    permissions: ["no-write", "planned"],
  },
  {
    id: "trae-cli",
    rank: 19,
    name: "TraeCode CLI",
    vendor: "字节跳动",
    category: "china-ecosystem",
    role: { zh: "厂商编码智能体", en: "Vendor coding agent" },
    description: {
      zh: "字节跳动 Trae 官方的命令行智能体；官方说明仅 Trae 企业版旗舰套餐可用，且默认走 Max 模式，接入前需先确认套餐与只读写法。",
      en: "ByteDance's official Trae command-line agent; per its docs it is limited to Trae enterprise flagship plans and defaults to Max mode, so both the plan and a read-only invocation must be settled before integration.",
    },
    docsUrl: "https://docs.trae.cn/cli_get-started-with-trae-cli",
    installHint: "irm https://trae.cn/trae-cli/install.ps1 | iex",
    binaries: {
      win: [
        "traecli.cmd",
        "traecli.exe",
        "traecli",
        "trae-cli.cmd",
        "trae-cli",
      ],
      unix: ["traecli", "trae-cli"],
    },
    permissions: ["no-write", "planned"],
  },
];
